/* =========================================================
   PEPTIDES — single source of truth
   Full monograph data. Used by index.html, wiki.html, quiz.html.
   ========================================================= */
window.PEPTIDES = [
  {
    id: "bpc-157", n: "BPC-157", code: "PEP-001", cats: ["Recovery"], tag: "Healing",
    cas: "137525-51-0", mw: "1419.55", half: "~4 hr", route: "Sub-Q", tier: "S", residues: "15-mer · pentadecapeptide",
    seq: "Gly-Glu-Pro-Pro-Pro-Gly-Lys-Pro-Ala-Asp-Asp-Ala-Gly-Leu-Val",
    short: "Pentadecapeptide derived from gastric juice — accelerates soft-tissue and gut healing via VEGFR-2 upregulation.",
    mechanism: "Partial sequence of body protection compound (BPC) isolated from gastric juice. Accelerates angiogenesis via VEGFR-2 upregulation, modulates the NO-system, and increases growth-hormone receptor expression on tendon fibroblasts — meaning it routes healing signals directly to soft tissue under load.",
    effects: ["Tendon & ligament repair", "Gastric ulcer healing", "Gut barrier integrity", "Neuroprotection (animal models)", "Vascular regeneration", "Counters NSAID-induced damage"],
    typical: "250–500 µg, 1–2× daily",
    cycle: "4–8 weeks, then 4 wk off",
    protocol: [
      { d: "01", v: "250 µg sub-Q · AM, near injury site", t: "loading" },
      { d: "07", v: "500 µg sub-Q · AM + PM", t: "peak loading" },
      { d: "21", v: "500 µg sub-Q · AM", t: "maintenance" },
      { d: "28", v: "250 µg sub-Q · taper week", t: "deload" },
      { d: "56", v: "— off-cycle —", t: "re-evaluate" },
    ],
    stacks: ["tb-500", "ghk-cu", "ipamorelin"],
    refs: [
      { t: "Sikiric et al — Stable gastric pentadecapeptide BPC 157", j: "Curr Med Chem", y: 2011 },
      { t: "Chang et al — BPC 157 & tendon-to-bone healing in rats", j: "J Appl Physiol", y: 2011 },
      { t: "Gwyer et al — Gastric pentadecapeptide BPC 157 and tendon repair", j: "Cell Tissue Res", y: 2019 },
    ],
    notes: "Research-chemical status. Not FDA-approved for human use. Stable to gastric acid (oral bioavailability under investigation; subcutaneous is the studied route). Always consult a physician.",
  },
  {
    id: "tb-500", n: "TB-500", code: "PEP-002", cats: ["Recovery", "Muscle"], tag: "Repair",
    cas: "77591-33-4", mw: "4963 Da", half: "2–3 days", route: "Sub-Q / IM", tier: "S", residues: "43-mer · Thymosin β-4 fragment",
    seq: "Ac-Ser-Asp-Lys-Pro-Asp-Met-Ala-Glu-Ile…",
    short: "Synthetic fragment of Thymosin Beta-4 — promotes cell migration to injury sites and accelerates wound repair.",
    mechanism: "TB-500 is the active fragment of Thymosin Beta-4. Binds G-actin, promoting actin polymerization required for cell migration to injury sites. Upregulates myocyte stem cells, accelerates angiogenesis, and dampens inflammatory cytokines.",
    effects: ["Cell migration to injury sites", "Angiogenesis", "Reduced scar tissue", "Hair follicle activation", "Muscle fiber repair"],
    typical: "2–5 mg per loading dose",
    cycle: "2× weekly × 4–6 wk loading, then 1× weekly maintenance",
    protocol: [
      { d: "01", v: "5 mg sub-Q · loading", t: "wk 1 day 1" },
      { d: "04", v: "5 mg sub-Q · loading", t: "wk 1 day 4" },
      { d: "08–28", v: "5 mg sub-Q · 2× wk", t: "loading phase" },
      { d: "29+", v: "2.5 mg sub-Q · 1× wk", t: "maintenance" },
    ],
    stacks: ["bpc-157", "ghk-cu", "ipamorelin"],
    refs: [
      { t: "Goldstein et al — Thymosin β4: actin-sequestering protein", j: "Ann N Y Acad Sci", y: 2012 },
      { t: "Crockford et al — Tβ4 in tissue repair", j: "Ann N Y Acad Sci", y: 2010 },
    ],
    notes: "Pairs synergistically with BPC-157. Long half-life means weekly dosing maintains steady levels.",
  },
  {
    id: "sermorelin", n: "Sermorelin", code: "PEP-003", cats: ["Muscle", "Anti-Aging", "Sleep"], tag: "GH pulse",
    cas: "86168-78-7", mw: "3358 Da", half: "~12 min", route: "Sub-Q PM", tier: "S", residues: "29-mer · GHRH (1–29)",
    seq: "Tyr-Ala-Asp-Ala-Ile-Phe-Thr-Asn-Ser-Tyr-Arg-Lys-Val-Leu-Gly-Gln-Leu-Ser-Ala-Arg-Lys-Leu-Leu-Gln-Asp-Ile-Met-Ser-Arg",
    short: "29-aa GHRH analog that stimulates the pituitary to release endogenous growth hormone in pulses.",
    mechanism: "Truncated GHRH (1–29) — the minimum active fragment. Binds the GHRH receptor on pituitary somatotrophs, triggering endogenous GH release that respects natural negative feedback (no shutdown of the HPA axis like exogenous GH).",
    effects: ["Pulsed GH release", "Improved deep sleep", "Body composition shifts (lean ↑, fat ↓)", "Improved skin / collagen", "Better recovery"],
    typical: "200–300 µg, 5×/week",
    cycle: "12+ weeks ongoing — cycle off every 6 mo",
    protocol: [
      { d: "01", v: "200 µg sub-Q · pre-bed (empty stomach)", t: "build" },
      { d: "14", v: "300 µg sub-Q · pre-bed", t: "standard" },
      { d: "Mon–Fri", v: "300 µg sub-Q · pre-bed", t: "weekend off" },
      { d: "+6 mo", v: "4 wk wash-out", t: "cycle reset" },
    ],
    stacks: ["ipamorelin", "cjc-1295", "epithalon"],
    refs: [
      { t: "Walker — Sermorelin: a better approach to GH replacement?", j: "Curr Med Res Opin", y: 2006 },
      { t: "Khorram et al — GHRH effects on sleep architecture", j: "Sleep", y: 1997 },
    ],
    notes: "Empty stomach for 2 hr before/after dose. Pre-bed timing aligns with natural GH pulse during slow-wave sleep.",
  },
  {
    id: "cjc-1295", n: "CJC-1295 / DAC", code: "PEP-004", cats: ["Muscle", "Anti-Aging", "Fat Loss"], tag: "Long-acting",
    cas: "863288-34-0", mw: "3647 Da", half: "~8 days", route: "Sub-Q wk", tier: "S", residues: "30-mer · GHRH analog + DAC",
    seq: "Tyr-D-Ala-Asp-Ala-Ile-Phe-Thr-Gln-Ser-Tyr-Arg-Lys-Val-Leu-Ala-Gln-Leu-Ser-Ala-Arg-Lys-Leu-Leu-Gln-Asp-Ile-Leu-Ser-Arg-(Lys-DAC)",
    short: "Long-acting GHRH analog with Drug Affinity Complex — extends half-life from minutes to ~8 days for sustained GH elevation.",
    mechanism: "Modified GHRH(1–29) with four amino-acid swaps for protease resistance, plus a DAC (Drug Affinity Complex) maleimide linker that covalently binds serum albumin. Half-life jumps from ~7 min to ~8 days, producing a constant 'GH bleed' rather than pulses.",
    effects: ["Sustained GH elevation", "Higher IGF-1 baseline", "Body recomp", "Anti-aging skin / sleep effects"],
    typical: "1–2 mg weekly",
    cycle: "12 weeks on / 4 weeks off",
    protocol: [
      { d: "01", v: "1 mg sub-Q · once", t: "loading" },
      { d: "07", v: "1 mg sub-Q · weekly", t: "maintenance" },
      { d: "+12 wk", v: "Off-cycle 4 wk", t: "axis reset" },
    ],
    stacks: ["ipamorelin", "bpc-157"],
    refs: [
      { t: "Teichman et al — Prolonged stimulation of GH and IGF-I secretion by CJC-1295", j: "J Clin Endocrinol Metab", y: 2006 },
    ],
    notes: "Often paired with Ipamorelin for GH pulse on top of the bleed. The 'no-DAC' variant (Modified GRF 1-29) has a short half-life (~30 min) and is dosed differently.",
  },
  {
    id: "ipamorelin", n: "Ipamorelin", code: "PEP-007", cats: ["Muscle", "Recovery", "Anti-Aging"], tag: "Clean GH",
    cas: "170851-70-4", mw: "711.85", half: "~2 hr", route: "Sub-Q", tier: "S", residues: "5-mer · GHRP",
    seq: "Aib-His-D-2-Nal-D-Phe-Lys-NH₂",
    short: "Selective GH secretagogue and ghrelin mimetic that triggers a clean GH pulse without raising cortisol or prolactin.",
    mechanism: "Selective ghrelin receptor (GHSR-1a) agonist. Triggers GH release via the somatotrophs but — unlike GHRP-2/6 — does not activate the cortisol or prolactin axes. The 'cleanest' GHRP available.",
    effects: ["GH pulse", "Improved sleep depth", "Joint comfort", "Body recomp", "No hunger spike"],
    typical: "200–300 µg, 1–3×/day",
    cycle: "Ongoing with cycle weeks off every 12 wk",
    protocol: [
      { d: "01", v: "200 µg sub-Q · AM (empty)", t: "build" },
      { d: "+7", v: "200 µg sub-Q · AM + post-train + pre-bed", t: "3× daily" },
      { d: "Stack", v: "+ CJC-1295 (no DAC) 100 µg per dose", t: "synergy" },
    ],
    stacks: ["cjc-1295", "sermorelin", "bpc-157"],
    refs: [
      { t: "Raun et al — Ipamorelin, the first selective GHRP", j: "Eur J Endocrinol", y: 1998 },
    ],
    notes: "Standard 1:2 ratio with CJC-1295 (no DAC) for amplified GH pulse. Empty stomach before/after.",
  },
  {
    id: "ghk-cu", n: "GHK-Cu", code: "PEP-018", cats: ["Anti-Aging", "Recovery"], tag: "Remodel",
    cas: "49557-75-7", mw: "340.4 Da", half: "~3 hr", route: "Sub-Q / topical", tier: "A", residues: "3-mer · tripeptide-1",
    seq: "Gly-His-Lys + Cu²⁺",
    short: "Copper-binding tripeptide naturally found in human plasma — strong skin remodeling, hair, and anti-aging effects.",
    mechanism: "Naturally occurring tripeptide that binds copper(II). Modulates ~4,000 genes towards a younger expression profile. Stimulates dermal fibroblast collagen production, activates hair follicle stem cells, and upregulates antioxidant pathways.",
    effects: ["Skin elasticity & wrinkle reduction", "Hair growth (follicle activation)", "Wound healing", "Antioxidant effect", "Anti-inflammatory"],
    typical: "1–2 mg sub-Q + topical",
    cycle: "Continuous",
    protocol: [
      { d: "AM", v: "1 mg sub-Q · daily", t: "systemic" },
      { d: "AM/PM", v: "0.05% topical · face/scalp", t: "local" },
    ],
    stacks: ["bpc-157", "tb-500"],
    refs: [
      { t: "Pickart & Margolina — GHK Peptide as a Natural Modulator of Multiple Cellular Pathways", j: "Biomed Res Int", y: 2015 },
    ],
    notes: "Copper-bound version is bluish in solution. Topical formulations are widely used in cosmetics; injectable is the research-chem version.",
  },
  {
    id: "semax", n: "Semax", code: "PEP-014", cats: ["Cognition"], tag: "BDNF",
    cas: "80714-61-0", mw: "813.9 Da", half: "~30 min", route: "Intranasal", tier: "S", residues: "7-mer · ACTH 4–10 analog",
    seq: "Met-Glu-His-Phe-Pro-Gly-Pro",
    short: "Russian nootropic peptide derived from ACTH — boosts BDNF and supports cognition, mood, and neuroprotection.",
    mechanism: "Heptapeptide analog of ACTH(4–10) with proline-glycine-proline added for protease resistance. Increases BDNF expression in the hippocampus, modulates dopamine and serotonin turnover, and exerts neuroprotective effects in stroke models.",
    effects: ["BDNF upregulation", "Improved focus & memory", "Mood lift", "Neuroprotection", "Stroke rehabilitation (clinical use in Russia)"],
    typical: "300–600 µg intranasal, 1–2×/day",
    cycle: "2–4 weeks on / 1 week off",
    protocol: [
      { d: "AM", v: "300 µg intranasal", t: "primary" },
      { d: "Midday", v: "300 µg intranasal (optional)", t: "extend" },
    ],
    stacks: ["selank", "dihexa", "cerebrolysin"],
    refs: [
      { t: "Kaplan et al — Semax in Russian clinical practice", j: "Neurosci Behav Physiol", y: 2007 },
      { t: "Asmarin et al — Semax & BDNF expression", j: "Neurosci Lett", y: 2008 },
    ],
    notes: "Intranasal route. Pairs well with Selank (anxiolytic balance). Schedule for Day cognition only — can interfere with sleep if late.",
  },
  {
    id: "selank", n: "Selank", code: "PEP-015", cats: ["Cognition"], tag: "Anxiolytic",
    cas: "129954-34-3", mw: "751.9 Da", half: "~1 hr", route: "Intranasal", tier: "A", residues: "7-mer · tuftsin analog",
    seq: "Thr-Lys-Pro-Arg-Pro-Gly-Pro",
    short: "Russian-developed anxiolytic heptapeptide — analog of tuftsin with cognitive and immunomodulatory effects.",
    mechanism: "Heptapeptide modeled on tuftsin (a natural immunomodulator) with PGP added for stability. Modulates GABAergic transmission and increases BDNF — produces calm focus without the sedation or dependency of benzodiazepines in research models.",
    effects: ["Anxiety reduction", "Calm focus", "Immune modulation", "Improved learning"],
    typical: "300 µg intranasal, 2–3×/day",
    cycle: "2–4 weeks on / 1 week off",
    protocol: [
      { d: "AM", v: "300 µg intranasal", t: "anxiolytic" },
      { d: "Midday", v: "300 µg intranasal", t: "extend" },
    ],
    stacks: ["semax"],
    refs: [
      { t: "Inozemtsev et al — Selank effect on memory & anxiety", j: "Bull Exp Biol Med", y: 2008 },
    ],
    notes: "Often stacked with Semax (Selank AM, Semax mid-AM) for balanced calm-focus.",
  },
  {
    id: "pt-141", n: "PT-141", code: "PEP-008", cats: ["Libido"], tag: "MC4R",
    cas: "189691-06-3", mw: "1025.2 Da", half: "~2 hr", route: "Sub-Q", tier: "S", residues: "7-mer · α-MSH analog",
    seq: "Ac-Nle-cyclo[Asp-His-D-Phe-Arg-Trp-Lys]-OH",
    short: "Bremelanotide — a melanocortin agonist that acts on the central nervous system to enhance sexual arousal in both sexes.",
    mechanism: "Cyclic heptapeptide agonist at melanocortin receptors (primarily MC4R and MC3R). Acts centrally on the hypothalamus to increase sexual arousal and desire. Unlike PDE5 inhibitors, it doesn't act on vascular smooth muscle.",
    effects: ["Increased libido (CNS-mediated)", "Improved sexual response", "Mild appetite suppression"],
    typical: "1.5–2 mg sub-Q, PRN",
    cycle: "PRN — not chronic",
    protocol: [
      { d: "PRN", v: "1.5–2 mg sub-Q · 30–60 min before activity", t: "do not exceed 8/mo" },
    ],
    stacks: ["kisspeptin", "oxytocin"],
    refs: [
      { t: "Kingsberg et al — Bremelanotide for HSDD: RECONNECT study", j: "Obstet Gynecol", y: 2019 },
    ],
    notes: "FDA-approved (for HSDD in premenopausal women) — sold as Vyleesi. Common side effects: nausea (taper dose), darkening of moles/skin (Melanocortin 1 receptor cross-talk).",
  },
  {
    id: "epithalon", n: "Epithalon", code: "PEP-039", cats: ["Anti-Aging", "Sleep"], tag: "Telomere",
    cas: "307297-39-8", mw: "390.4 Da", half: "~30 min", route: "Sub-Q", tier: "S", residues: "4-mer · tetrapeptide",
    seq: "Ala-Glu-Asp-Gly",
    short: "Synthetic tetrapeptide that activates telomerase and supports pineal function — researched for longevity and circadian regulation.",
    mechanism: "Activates telomerase via interaction with the TERT gene promoter, lengthening telomeres in vitro. Supports pineal melatonin synthesis and modulates the hypothalamic-pituitary axis.",
    effects: ["Telomere lengthening (in vitro)", "Improved sleep architecture", "Melatonin support", "Possible lifespan extension (animal studies)"],
    typical: "5–10 mg sub-Q",
    cycle: "Pulse: 10 days on / 5–6 mo off",
    protocol: [
      { d: "01–10", v: "10 mg sub-Q · daily PM", t: "pulse cycle" },
      { d: "+5 mo", v: "Repeat 10-day pulse", t: "biannual" },
    ],
    stacks: ["sermorelin", "thymosin-a1", "mots-c"],
    refs: [
      { t: "Khavinson — Peptide regulation of aging and lifespan", j: "Bull Exp Biol Med", y: 2002 },
    ],
    notes: "Pulse-dose protocol — not chronic. Dr. Khavinson's original protocol is 10 days × 2/year. Russian gerontology research base.",
  },
  {
    id: "thymosin-a1", n: "Thymosin Alpha-1", code: "PEP-051", cats: ["Recovery", "Anti-Aging"], tag: "Immune",
    cas: "62304-98-7", mw: "3108 Da", half: "~2 hr", route: "Sub-Q", tier: "A", residues: "28-mer",
    seq: "Ac-Ser-Asp-Ala-Ala-Val-Asp-Thr-Ser-Ser-Glu-Ile-Thr-Thr-Lys-Asp-Leu-Lys-Glu-Lys-Lys-Glu-Val-Val-Glu-Glu-Ala-Glu-Asn",
    short: "28-aa peptide that modulates innate and adaptive immunity — used clinically for hepatitis and immune support.",
    mechanism: "Naturally produced by the thymus. Activates T-cell maturation and dendritic cells; modulates Th1/Th2 balance. Used clinically in 35+ countries for hepatitis B/C and as adjuvant for cancer therapy and severe infections.",
    effects: ["T-cell function ↑", "Anti-viral immunity", "Adjuvant for vaccines", "Modulation of autoimmunity"],
    typical: "1.6 mg sub-Q",
    cycle: "2× weekly × 12 wk",
    protocol: [
      { d: "Mon", v: "1.6 mg sub-Q", t: "weekly 1" },
      { d: "Thu", v: "1.6 mg sub-Q", t: "weekly 2" },
    ],
    stacks: ["bpc-157", "epithalon"],
    refs: [
      { t: "Garaci et al — Thymosin alpha 1: from bench to bedside", j: "Ann N Y Acad Sci", y: 2007 },
    ],
    notes: "Approved (Zadaxin) in 35+ countries for hepatitis B/C. Not FDA-approved in the US.",
  },
  {
    id: "tirzepatide", n: "Tirzepatide", code: "PEP-201", cats: ["Fat Loss"], tag: "GLP-1 / GIP",
    cas: "2023788-19-2", mw: "4813.5 Da", half: "~5 days", route: "Sub-Q wk", tier: "S", residues: "39-mer",
    seq: "(complex, fatty-acid-modified)",
    short: "Dual GIP/GLP-1 receptor agonist (Mounjaro / Zepbound) — currently the most effective injectable for body-weight reduction.",
    mechanism: "Dual agonist at the GLP-1 and GIP receptors. The GIP arm appears to amplify the GLP-1 satiety effect while improving energy expenditure. Slows gastric emptying, increases insulin secretion, and reduces food intake centrally.",
    effects: ["Profound satiety", "Weight loss (15–22% in trials)", "Glycemic control", "Improved cardiovascular markers"],
    typical: "2.5 → 5 → 10 → 15 mg weekly",
    cycle: "Ongoing — taper to off if discontinuing",
    protocol: [
      { d: "Wk 1–4", v: "2.5 mg sub-Q · 1× wk", t: "starter" },
      { d: "Wk 5–8", v: "5 mg sub-Q · 1× wk", t: "step 1" },
      { d: "Wk 9–12", v: "7.5 mg sub-Q · 1× wk", t: "step 2" },
      { d: "Wk 13+", v: "10–15 mg sub-Q · 1× wk", t: "maintenance (titrate)" },
    ],
    stacks: ["aod-9604", "mots-c", "bpc-157"],
    refs: [
      { t: "Jastreboff et al — SURMOUNT-1: Tirzepatide once weekly for obesity", j: "NEJM", y: 2022 },
    ],
    notes: "FDA-approved (Mounjaro for T2D, Zepbound for obesity). Taper if discontinuing — abrupt stop = rapid weight regain. Pair with resistance training to preserve muscle.",
  },
  {
    id: "semaglutide", n: "Semaglutide", code: "PEP-202", cats: ["Fat Loss"], tag: "GLP-1",
    cas: "910463-68-2", mw: "4113.6 Da", half: "~7 days", route: "Sub-Q wk", tier: "S", residues: "31-mer",
    seq: "(fatty-acid-modified GLP-1 analog)",
    short: "Long-acting GLP-1 receptor agonist (Ozempic / Wegovy) — drives satiety and glucose control with potent body-weight reduction.",
    mechanism: "GLP-1 analog with C-18 fatty acid for albumin binding (extends half-life to ~7 days). Activates GLP-1 receptors to slow gastric emptying, suppress glucagon, increase insulin sensitivity, and reduce food intake centrally.",
    effects: ["Satiety", "Weight loss (~12–15% in trials)", "Glycemic control", "Cardiovascular protection"],
    typical: "0.25 → 0.5 → 1 → 2.4 mg weekly",
    cycle: "Ongoing",
    protocol: [
      { d: "Wk 1–4", v: "0.25 mg sub-Q · 1× wk", t: "starter" },
      { d: "Wk 5–8", v: "0.5 mg sub-Q · 1× wk", t: "step 1" },
      { d: "Wk 9–12", v: "1 mg sub-Q · 1× wk", t: "step 2" },
      { d: "Wk 13+", v: "2.4 mg sub-Q · 1× wk", t: "maintenance" },
    ],
    stacks: ["mots-c", "aod-9604"],
    refs: [
      { t: "Wilding et al — STEP-1: Semaglutide once weekly for obesity", j: "NEJM", y: 2021 },
    ],
    notes: "FDA-approved (Ozempic for T2D, Wegovy for obesity, Rybelsus oral version). Common GI side effects on titration up.",
  },
  {
    id: "mots-c", n: "MOTS-c", code: "PEP-079", cats: ["Fat Loss", "Anti-Aging"], tag: "Mito",
    cas: "1627580-64-6", mw: "2174 Da", half: "~3 hr", route: "Sub-Q", tier: "A", residues: "16-mer · mitochondrial-derived",
    seq: "Met-Arg-Trp-Gln-Glu-Met-Gly-Tyr-Ile-Phe-Tyr-Pro-Arg-Lys-Leu-Arg",
    short: "16-aa mitochondrial-derived peptide that signals via AMPK — improves metabolic flexibility, insulin sensitivity, and exercise capacity.",
    mechanism: "Encoded in the mitochondrial 12S rRNA region. Activates AMPK (the master metabolic switch), improves insulin sensitivity, drives fatty-acid oxidation, and enhances exercise capacity. Levels decline with age.",
    effects: ["Insulin sensitivity ↑", "Metabolic flexibility", "Exercise capacity", "Counters age-related metabolic decline"],
    typical: "5–10 mg sub-Q",
    cycle: "3× weekly × 8–12 wk",
    protocol: [
      { d: "Mon/Wed/Fri", v: "10 mg sub-Q", t: "loading 4 wk" },
      { d: "+4 wk", v: "5 mg sub-Q · 3× wk", t: "maintenance" },
    ],
    stacks: ["epithalon", "tirzepatide", "thymosin-a1"],
    refs: [
      { t: "Lee et al — The mitochondrial-derived peptide MOTS-c promotes metabolic homeostasis", j: "Cell Metab", y: 2015 },
    ],
    notes: "Truly fascinating — endogenous peptide whose levels decline with age. Rapidly becoming a longevity-stack staple.",
  },
  {
    id: "dsip", n: "DSIP", code: "PEP-040", cats: ["Sleep"], tag: "Delta",
    cas: "62568-57-4", mw: "850 Da", half: "~7 min", route: "Sub-Q PM", tier: "A", residues: "9-mer · nonapeptide",
    seq: "Trp-Ala-Gly-Gly-Asp-Ala-Ser-Gly-Glu",
    short: "Delta Sleep-Inducing Peptide — a nonapeptide that promotes delta-wave (deep) sleep and modulates stress response.",
    mechanism: "Naturally occurring nonapeptide first isolated from rabbit brain. Promotes delta-wave EEG activity, modulates the HPA axis (lowering cortisol), and may have analgesic effects. Crosses the BBB despite its size.",
    effects: ["Increased delta-wave sleep", "Reduced sleep latency", "Lower cortisol", "Mild analgesia"],
    typical: "100–200 µg sub-Q pre-bed",
    cycle: "Continuous or PRN",
    protocol: [
      { d: "PM", v: "100 µg sub-Q · 30 min pre-bed", t: "build" },
      { d: "+1 wk", v: "200 µg sub-Q · 30 min pre-bed", t: "standard" },
    ],
    stacks: ["sermorelin", "epithalon"],
    refs: [
      { t: "Schneider-Helmert & Schoenenberger — DSIP as a sleep-promoting agent", j: "Eur J Pharmacol", y: 1986 },
    ],
    notes: "Short half-life is a feature, not a bug — does its job before you fall asleep, then clears.",
  },
  {
    id: "tesamorelin", n: "Tesamorelin", code: "PEP-019", cats: ["Fat Loss", "Anti-Aging"], tag: "Visceral",
    cas: "218949-48-5", mw: "5135.8 Da", half: "~26 min", route: "Sub-Q", tier: "A", residues: "44-mer · GHRH analog",
    short: "Stabilized GHRH analog approved for HIV-related visceral fat reduction — strong lipolytic effect on belly fat.",
    mechanism: "Trans-3-hexenoyl-modified GHRH (1–44). Resists rapid degradation. Stimulates GH/IGF-1 axis, with a notable preference for visceral fat reduction without affecting subcutaneous fat dramatically.",
    effects: ["Visceral adipose reduction", "Improved lipid profile", "GH/IGF-1 elevation"],
    typical: "1–2 mg sub-Q daily",
    cycle: "12+ wk continuous",
    protocol: [
      { d: "01", v: "1 mg sub-Q · pre-bed", t: "build" },
      { d: "+14", v: "2 mg sub-Q · pre-bed", t: "standard" },
    ],
    stacks: ["ipamorelin", "mots-c"],
    refs: [
      { t: "Falutz et al — Tesamorelin for visceral fat in HIV", j: "NEJM", y: 2007 },
    ],
    notes: "FDA-approved for HIV-associated lipodystrophy (Egrifta). Off-label use for general visceral fat is common.",
  },
  {
    id: "hexarelin", n: "Hexarelin", code: "PEP-022", cats: ["Muscle", "Anti-Aging"], tag: "Cardio",
    cas: "140703-51-1", mw: "887.05", half: "~70 min", route: "Sub-Q", tier: "A", residues: "6-mer · GHRP",
    seq: "His-D-2-Me-Trp-Ala-Trp-D-Phe-Lys-NH₂",
    short: "Most potent GH secretagogue per mcg in the GHRP family, with notable cardioprotective effects in research models.",
    mechanism: "GHRP family — most potent GH secretagogue per mcg. Binds GHSR-1a and CD36 receptors; the latter underlies its observed cardioprotective effects in ischemia models.",
    effects: ["Strong GH pulse", "Cardioprotection (CD36-mediated)", "IGF-1 elevation"],
    typical: "100 µg sub-Q",
    cycle: "8 wk on / 4 wk off (desensitization risk)",
    protocol: [
      { d: "AM", v: "100 µg sub-Q", t: "primary" },
      { d: "Post-train", v: "100 µg sub-Q", t: "optional 2nd" },
    ],
    stacks: ["cjc-1295", "ipamorelin"],
    refs: [
      { t: "Locatelli et al — Hexarelin: a peptide GHRP", j: "Pharmacol Res", y: 1995 },
    ],
    notes: "Down-regulates GHSR-1a faster than Ipamorelin — strict cycling required. Not for chronic daily use.",
  },
  {
    id: "ghrp-2", n: "GHRP-2", code: "PEP-020", cats: ["Muscle", "Anti-Aging"], tag: "GH pulse",
    cas: "158861-67-7", mw: "817.94", half: "~1 hr", route: "Sub-Q", tier: "B", residues: "6-mer · GHRP",
    short: "Potent ghrelin-mimetic GH secretagogue that triggers strong GH pulses, with a mild rise in cortisol and prolactin.",
    mechanism: "Synthetic ghrelin mimetic at GHSR-1a. More potent GH release than Ipamorelin but with a small bump in cortisol and prolactin.",
    effects: ["Strong GH pulse", "Mild appetite increase", "IGF-1 elevation"],
    typical: "100–200 µg sub-Q, 2–3×/day",
    cycle: "8 wk on / 4 wk off",
    stacks: ["cjc-1295", "sermorelin"],
    notes: "Older-generation GHRP. Ipamorelin generally preferred unless you specifically want the appetite effect.",
  },
  {
    id: "ghrp-6", n: "GHRP-6", code: "PEP-021", cats: ["Muscle", "Recovery"], tag: "Hunger",
    cas: "87616-84-0", mw: "873.01", half: "~1 hr", route: "Sub-Q", tier: "B", residues: "6-mer · GHRP",
    short: "Older-generation ghrelin-mimetic GH secretagogue — strong GH release with notable hunger and prolactin/cortisol activity.",
    mechanism: "First-generation GHRP. Strong GH release accompanied by significant ghrelin-driven hunger. Useful when bulking; less ideal when cutting.",
    effects: ["GH pulse", "Strong appetite stimulation", "Recovery support"],
    typical: "100 µg sub-Q",
    cycle: "8 wk on / 4 wk off",
    stacks: ["cjc-1295"],
    notes: "Largely superseded by Ipamorelin and GHRP-2, but still preferred by some bulking protocols.",
  },
  {
    id: "mgf", n: "MGF (Mechano Growth Factor)", code: "PEP-091", cats: ["Muscle", "Recovery"], tag: "Local",
    cas: "complex", mw: "8907 Da", half: "~7 min", route: "IM local", tier: "A", residues: "IGF-1 splice variant",
    short: "Splice variant of IGF-1 expressed in muscle in response to mechanical loading — drives satellite-cell activation and local hypertrophy.",
    mechanism: "Local IGF-1 isoform expressed by mechanically loaded muscle. Activates satellite cells (muscle stem cells) for site-specific hypertrophy.",
    effects: ["Satellite cell activation", "Local hypertrophy", "Muscle repair"],
    typical: "200 µg IM at the trained muscle",
    cycle: "Post-training 3–4×/wk",
    stacks: ["igf-1-lr3", "bpc-157"],
    notes: "Very short half-life — must be injected near the target muscle immediately post-training.",
  },
  {
    id: "igf-1-lr3", n: "IGF-1 LR3", code: "PEP-114", cats: ["Muscle"], tag: "Anabolic",
    cas: "946870-92-4", mw: "9111 Da", half: "20–30 hr", route: "Sub-Q", tier: "S", residues: "83-mer · long-acting IGF-1",
    short: "Long-acting IGF-1 analog with reduced binding to IGFBPs — systemic anabolic signaling for hours rather than minutes.",
    mechanism: "Modified IGF-1 with N-terminal extension and an Arg substitution — reduced affinity for binding proteins extends half-life dramatically.",
    effects: ["Systemic anabolic signaling", "Muscle hypertrophy", "Improved nutrient partitioning"],
    typical: "20–50 µg sub-Q daily",
    cycle: "4–6 wk on / 4 wk off",
    stacks: ["mgf", "cjc-1295"],
    notes: "Powerful — and powerful side effects (hypoglycemia risk). Not for casual use. Cycle strictly.",
  },
  {
    id: "igf-1-des", n: "IGF-1 DES (1,3)", code: "PEP-115", cats: ["Muscle", "Recovery"], tag: "Local",
    mw: "7649 Da", half: "~20 min", route: "IM local", tier: "B", residues: "67-mer",
    short: "Truncated IGF-1 analog with very short systemic activity but high local potency — used for site-specific muscle growth.",
    mechanism: "Truncated IGF-1 lacking residues 1–3. Cannot bind IGFBPs effectively, so it works locally and clears quickly.",
    effects: ["Local hypertrophy", "Site-specific signaling"],
    typical: "50–100 µg IM local",
    cycle: "Post-training 3×/wk",
    stacks: ["mgf"],
    notes: "Dose at the trained muscle. Short systemic exposure reduces hypoglycemia risk vs. LR3.",
  },
  {
    id: "liraglutide", n: "Liraglutide", code: "PEP-203", cats: ["Fat Loss"], tag: "GLP-1",
    cas: "204656-20-2", mw: "3751.2 Da", half: "~13 hr", route: "Sub-Q daily", tier: "B", residues: "31-mer",
    short: "First-generation GLP-1 receptor agonist (Saxenda / Victoza) — daily-injection predecessor to semaglutide with a shorter half-life.",
    mechanism: "GLP-1 analog with a fatty-acid linker for albumin binding. Daily dose; superseded clinically by semaglutide for most uses.",
    effects: ["Satiety", "Weight loss (~5–8% in trials)", "Glycemic control"],
    typical: "0.6 → 3.0 mg sub-Q daily",
    cycle: "Ongoing",
    stacks: ["mots-c"],
    notes: "FDA-approved (Saxenda for obesity, Victoza for T2D). Generally reserved for those who don't tolerate semaglutide.",
  },
  {
    id: "aod-9604", n: "AOD-9604", code: "PEP-006", cats: ["Fat Loss"], tag: "Lipolytic",
    cas: "221231-10-3", mw: "1815.1 Da", half: "~30 min", route: "Sub-Q", tier: "B", residues: "16-mer · GH C-terminus fragment",
    short: "Modified C-terminus fragment of human GH (similar lineage to Frag 176-191) with fat-loss focus and added stability.",
    mechanism: "Stabilized fragment of the C-terminal end of human GH. Triggers lipolysis without GH-receptor anabolic / proliferative effects.",
    effects: ["Lipolysis (visceral & SC fat)", "No appetite increase", "No insulin resistance"],
    typical: "300 µg sub-Q AM fasted",
    cycle: "12 wk continuous",
    stacks: ["tirzepatide", "mots-c"],
    notes: "Best results when injected fasted, 30 min before cardio.",
  },
  {
    id: "hgh-frag", n: "HGH Frag 176-191", code: "PEP-005", cats: ["Fat Loss"], tag: "Lipolytic",
    mw: "1817 Da", half: "~30 min", route: "Sub-Q", tier: "B", residues: "16-mer · GH(176-191)",
    short: "Truncated fragment of growth hormone (residues 176-191) that retains fat-burning effects without GH-related growth signaling.",
    mechanism: "Synthetic 16-aa fragment corresponding to GH residues 176–191. Stimulates lipolysis without IGF-1 elevation or growth signaling.",
    effects: ["Lipolysis", "No IGF-1 elevation"],
    typical: "200–500 µg sub-Q",
    cycle: "12 wk continuous",
    stacks: ["aod-9604"],
    notes: "Predecessor / cousin of AOD-9604. Both target lipolysis without anabolic effect.",
  },
  {
    id: "kisspeptin", n: "Kisspeptin", code: "PEP-058", cats: ["Libido", "Muscle"], tag: "HPG",
    cas: "1356810-20-4", mw: "1302.5 Da", half: "~30 min", route: "Sub-Q", tier: "A", residues: "10-mer · KP-10",
    short: "Upstream regulator of the HPG axis — stimulates GnRH release, driving LH/FSH and downstream sex hormone production.",
    mechanism: "Kisspeptin-10 binds the KISS1R (GPR54) on hypothalamic GnRH neurons. Triggers pulsatile GnRH release, which drives LH/FSH from the pituitary, and ultimately testosterone or estrogen.",
    effects: ["LH/FSH ↑", "Endogenous testosterone ↑", "Sexual response (CNS modulation)"],
    typical: "200 µg sub-Q",
    cycle: "Daily × 4–8 wk",
    stacks: ["pt-141", "oxytocin"],
    notes: "Re-engages a suppressed HPG axis. Useful post-cycle or for low libido with normal-low testosterone.",
  },
  {
    id: "oxytocin", n: "Oxytocin", code: "PEP-060", cats: ["Libido"], tag: "Bonding",
    cas: "50-56-6", mw: "1007.2 Da", half: "~3 min", route: "Intranasal", tier: "B", residues: "9-mer · nonapeptide",
    seq: "Cys-Tyr-Ile-Gln-Asn-Cys-Pro-Leu-Gly-NH₂",
    short: "The 'bonding' nonapeptide — modulates social cognition, trust, sexual response, and empathy via central oxytocin receptors.",
    mechanism: "Nonapeptide with a disulfide bridge. Synthesized in the hypothalamus, released centrally and from posterior pituitary. Modulates pair-bonding, trust, sexual response, and labor.",
    effects: ["Pair bonding", "Trust", "Reduced social anxiety", "Sexual response modulation"],
    typical: "10–40 IU intranasal",
    cycle: "PRN",
    stacks: ["pt-141", "kisspeptin"],
    notes: "Intranasal is the only practical route for CNS effect. Effects subtle — easily confused with placebo without controlled use.",
  },
  {
    id: "melanotan-ii", n: "Melanotan II", code: "PEP-061", cats: ["Libido"], tag: "Tan/Libido",
    cas: "121062-08-6", mw: "1024.18", half: "~33 hr", route: "Sub-Q", tier: "B", residues: "7-mer · α-MSH analog",
    seq: "Ac-Nle-cyclo[Asp-His-D-Phe-Arg-Trp-Lys]-NH₂",
    short: "A non-selective melanocortin agonist that triggers tanning, libido enhancement, and appetite suppression via MC1R/MC3R/MC4R.",
    mechanism: "Cyclic heptapeptide agonist at MC1R (skin pigmentation), MC3R/MC4R (appetite, libido). Less selective than PT-141 — that's the point if you want both effects.",
    effects: ["Skin tanning", "Libido enhancement", "Appetite suppression", "Mole darkening"],
    typical: "0.25–0.5 mg sub-Q",
    cycle: "Loading phase + UV exposure",
    stacks: [],
    notes: "Cosmetic side effects (mole darkening, freckling) are common. Not for those with high mole density or melanoma risk.",
  },
  {
    id: "cerebrolysin", n: "Cerebrolysin", code: "PEP-066", cats: ["Cognition", "Anti-Aging"], tag: "Neurotrophic",
    mw: "complex", half: "varies", route: "IM / IV", tier: "A", residues: "porcine brain peptide complex",
    short: "Peptide complex derived from porcine brain proteins — neurotrophic and neuroprotective, used clinically for stroke recovery and dementia.",
    mechanism: "Standardized mixture of low-molecular-weight peptides and amino acids from porcine brain. Mimics neurotrophic factor effects (BDNF, NGF), promotes neurogenesis and synaptic plasticity.",
    effects: ["Neurogenesis", "Synaptic plasticity", "Stroke recovery", "Dementia symptom reduction"],
    typical: "5–30 mL IM/IV daily",
    cycle: "10–20 day courses",
    stacks: ["semax", "dihexa"],
    notes: "Approved in many countries (not US) for stroke and dementia. Evidence base is mixed — best evidence in acute stroke recovery.",
  },
  {
    id: "dihexa", n: "Dihexa", code: "PEP-067", cats: ["Cognition"], tag: "Synaptic",
    cas: "1401708-83-5", mw: "560.7 Da", half: "~10 hr", route: "Oral", tier: "A", residues: "6-mer · angiotensin IV analog",
    short: "Angiotensin-derived peptidomimetic with strong oral bioavailability and a profound effect on synaptic formation via HGF/c-Met.",
    mechanism: "Angiotensin IV-derived hexapeptide. Activates the HGF/c-Met receptor system, promoting synaptogenesis. ~7 orders of magnitude more potent than BDNF in synaptic formation assays.",
    effects: ["Synaptogenesis", "Improved memory in animal models", "Cognitive enhancement"],
    typical: "8–35 mg oral daily",
    cycle: "4–8 wk on / 2 wk off",
    stacks: ["semax", "cerebrolysin"],
    notes: "One of the few orally bioavailable cognitive peptides. Long human-safety data lacking — cycle conservatively.",
  },
  {
    id: "p21", n: "P21", code: "PEP-068", cats: ["Cognition", "Anti-Aging"], tag: "Neurogenesis",
    mw: "525.6 Da", half: "~4 hr", route: "Intranasal", tier: "B", residues: "4-mer · CNTF-derived",
    short: "A 4-aa peptide derived from CNTF — promotes neurogenesis and synaptic plasticity in research models.",
    mechanism: "Tetrapeptide derived from ciliary neurotrophic factor (CNTF). Bypasses CNTF's side-effect profile while retaining neurogenic activity.",
    effects: ["Neurogenesis (hippocampus)", "Cognitive support"],
    stacks: ["semax", "dihexa"],
    notes: "Limited human data. Promising in rodent neurogenesis models.",
  },
  {
    id: "foxo4-dri", n: "FOXO4-DRI", code: "PEP-082", cats: ["Anti-Aging"], tag: "Senolytic",
    mw: "5398 Da", half: "short", route: "Sub-Q", tier: "B", residues: "modified peptide",
    short: "A modified peptide that selectively kills senescent cells (senolytic) by disrupting the FOXO4-p53 interaction.",
    mechanism: "D-retro-inverso modified peptide that disrupts the FOXO4–p53 interaction in senescent cells, releasing p53 to trigger apoptosis selectively in those cells.",
    effects: ["Senescent cell clearance (in vitro / animal models)", "Possible reversal of aging markers"],
    stacks: ["epithalon", "mots-c"],
    notes: "Cutting-edge. Limited human-safety data. Pulse protocols only.",
  },
  {
    id: "humanin", n: "Humanin", code: "PEP-083", cats: ["Anti-Aging", "Cognition"], tag: "Mito",
    mw: "2687.2 Da", half: "~3 hr", route: "Sub-Q", tier: "B", residues: "24-mer · mitochondrial-derived",
    short: "A 24-aa mitochondrial-derived peptide with cytoprotective effects against neuronal death and metabolic stress.",
    mechanism: "Encoded in the mitochondrial 16S rRNA. Cytoprotective via inhibition of Bax-mediated apoptosis and modulation of inflammatory pathways.",
    effects: ["Neuroprotection", "Improved insulin sensitivity", "Cytoprotection"],
    stacks: ["mots-c", "epithalon"],
    notes: "Like MOTS-c, levels decline with age. Long-term human data lacking.",
  },
  {
    id: "amino-1mq", n: "5-Amino-1MQ", code: "PEP-090", cats: ["Fat Loss", "Anti-Aging"], tag: "NAD+",
    mw: "159.2 Da", half: "~6 hr", route: "Oral", tier: "B", residues: "small molecule (NNMT inhibitor)",
    short: "Small-molecule NNMT inhibitor (often grouped with peptide stacks) — increases NAD+ and supports fat loss + muscle preservation.",
    mechanism: "Selective inhibitor of nicotinamide N-methyltransferase (NNMT). Spares NAD+ precursors, increases NAD+ levels, and shifts metabolism towards fat oxidation.",
    effects: ["NAD+ elevation", "Fat oxidation ↑", "Muscle preservation"],
    stacks: ["mots-c"],
    notes: "Technically not a peptide. Included because the recomp / longevity crowd stacks it alongside peptides.",
  },
  {
    id: "ll-37", n: "LL-37", code: "PEP-094", cats: ["Recovery"], tag: "Antimicrobial",
    mw: "4493 Da", half: "~30 min", route: "Sub-Q", tier: "B", residues: "37-mer · cathelicidin",
    short: "Human cathelicidin peptide — antimicrobial, immunomodulatory, and being studied for chronic infection clearance.",
    mechanism: "The only human cathelicidin. Disrupts bacterial membranes; modulates immune response; promotes wound healing.",
    effects: ["Antimicrobial activity", "Wound healing", "Immune modulation"],
    stacks: ["thymosin-a1", "bpc-157"],
    notes: "Used by some for chronic Lyme / biofilm-associated infections. Evidence base is largely preclinical.",
  },
  {
    id: "snap-8", n: "SNAP-8", code: "PEP-095", cats: ["Anti-Aging"], tag: "Topical",
    mw: "889 Da", half: "topical", route: "Topical", tier: "B", residues: "8-mer",
    short: "Octapeptide that inhibits SNARE complex formation — cosmetic peptide for expression-line reduction.",
    mechanism: "Mimics the N-terminal of SNAP-25, competing with the natural protein in the SNARE complex. Reduces neurotransmitter release at neuromuscular junctions — topically, this softens expression lines.",
    effects: ["Expression line reduction (topical)"],
    stacks: ["ghk-cu"],
    notes: "Topical cosmetic peptide. The 'Botox-like' marketing is overhyped — effect is real but mild.",
  },
  {
    id: "argireline", n: "Argireline", code: "PEP-096", cats: ["Anti-Aging"], tag: "Topical",
    mw: "888.9 Da", half: "topical", route: "Topical", tier: "B", residues: "6-mer",
    short: "Hexapeptide cosmetic agent — topical SNARE modulator for fine lines.",
    mechanism: "Mimics the N-terminal of SNAP-25 (similar mechanism to SNAP-8). Reduces neurotransmitter release at facial muscles.",
    effects: ["Fine-line reduction (topical)"],
    stacks: ["ghk-cu"],
    notes: "Standard ingredient in 'peptide serums.' Mild effect.",
  },
  {
    id: "n-acetyl-snap8", n: "N-Acetyl SNAP-8", code: "PEP-097", cats: ["Anti-Aging"], tag: "Topical",
    mw: "931 Da", half: "topical", route: "Topical", tier: "B",
    short: "Acetylated SNAP-8 — improved skin penetration vs. base peptide.",
    notes: "Cosmetic-tier. Acetylation improves topical bioavailability.",
  },
  {
    id: "matrixyl", n: "Matrixyl (Palmitoyl Pentapeptide-4)", code: "PEP-098", cats: ["Anti-Aging"], tag: "Topical",
    mw: "802.1 Da", half: "topical", route: "Topical", tier: "A",
    short: "Palmitoyl-anchored pentapeptide — stimulates collagen and hyaluronic acid synthesis topically.",
    mechanism: "Pal-Lys-Thr-Thr-Lys-Ser. The palmitoyl tail anchors it in the stratum corneum; the peptide stimulates fibroblast collagen I, III, and IV plus HA.",
    effects: ["Collagen synthesis", "Wrinkle reduction", "Skin firmness"],
    notes: "One of the few cosmetic peptides with solid published data.",
  },
  {
    id: "vialox", n: "Vialox", code: "PEP-099", cats: ["Anti-Aging"], tag: "Topical",
    mw: "619 Da", half: "topical", route: "Topical", tier: "B",
    short: "Pentapeptide-3 — topical postsynaptic acetylcholine receptor antagonist.",
    notes: "Cosmetic muscle-relaxing peptide. Mild effect.",
  },
  {
    id: "tat-cn21", n: "Tat-CN21", code: "PEP-100", cats: ["Cognition"], tag: "CaMKII",
    mw: "~3000 Da", half: "~hours", route: "research-only", tier: "B",
    short: "CaMKII inhibitor peptide fused to TAT cell-penetrating sequence — research tool for synaptic plasticity studies.",
    notes: "Research reagent. Not for human use.",
  },
  {
    id: "khavinson-1", n: "Vesugen", code: "PEP-110", cats: ["Anti-Aging"], tag: "Vascular",
    mw: "~360 Da", half: "~30 min", route: "Sub-Q", tier: "B", residues: "tripeptide",
    short: "Khavinson tripeptide — researched for vascular endothelium support.",
    notes: "Khavinson family. Pulse protocols similar to Epithalon.",
  },
  {
    id: "khavinson-2", n: "Pinealon", code: "PEP-111", cats: ["Anti-Aging", "Cognition"], tag: "Pineal",
    mw: "~370 Da", half: "~30 min", route: "Sub-Q", tier: "B", residues: "tripeptide",
    short: "Khavinson pineal-targeted tripeptide — researched for cognitive aging and neuroprotection.",
    notes: "Khavinson family. Often paired with Epithalon for combined longevity stack.",
  },
  {
    id: "khavinson-3", n: "Cartalax", code: "PEP-112", cats: ["Recovery"], tag: "Cartilage",
    mw: "~360 Da", half: "~30 min", route: "Sub-Q", tier: "B", residues: "tripeptide",
    short: "Khavinson tripeptide — researched for cartilage and joint tissue regulation.",
    notes: "Khavinson family. Joint-focused.",
  },
  {
    id: "ara-290", n: "ARA-290", code: "PEP-120", cats: ["Recovery"], tag: "Neuropathy",
    mw: "1257 Da", half: "~2 min plasma", route: "Sub-Q", tier: "B", residues: "11-mer · EPO-derived",
    short: "Erythropoietin-derived 11-mer that activates the innate repair receptor without raising hematocrit.",
    mechanism: "Helix B Surface Peptide of EPO. Activates the innate repair receptor (IRR), driving cytoprotection and anti-inflammation without EPO's erythropoietic side effects.",
    effects: ["Neuropathy reduction (sarcoidosis trial data)", "Anti-inflammation", "Tissue repair"],
    notes: "Published Phase II data for small-fiber neuropathy. Niche but evidence-backed.",
  },
  {
    id: "follistatin", n: "Follistatin-344", code: "PEP-121", cats: ["Muscle"], tag: "Myostatin",
    mw: "~32 kDa", half: "~hours", route: "Sub-Q / IM", tier: "A", residues: "~344-mer protein",
    short: "Native myostatin antagonist — drives skeletal muscle growth by removing the myostatin brake.",
    mechanism: "Endogenous myostatin-binding protein. Sequesters myostatin, releasing the negative feedback brake on muscle growth.",
    effects: ["Muscle hypertrophy", "Reduced fibrosis"],
    notes: "Powerful and powerful side-effect risk. Not casual. Cycle strictly.",
  },
  {
    id: "ipam-glu", n: "Glutathione (GSH)", code: "PEP-130", cats: ["Anti-Aging", "Recovery"], tag: "Antiox",
    mw: "307.3 Da", half: "~30 min", route: "IV / Sub-Q / oral", tier: "A", residues: "tripeptide",
    seq: "γ-Glu-Cys-Gly",
    short: "The body's master antioxidant tripeptide — declines with age, supplemented for liver, immune, and cellular protection.",
    mechanism: "Tripeptide of γ-glutamate-cysteine-glycine. Direct antioxidant + cofactor for glutathione peroxidases. Detoxifies xenobiotics in the liver via Phase II conjugation.",
    effects: ["Antioxidant defense", "Liver detoxification", "Immune support", "Skin brightening (IV protocols)"],
    typical: "IV: 600–2000 mg per session",
    stacks: ["mots-c", "epithalon"],
    notes: "Oral bioavailability is poor (degraded in gut). IV / sub-Q / liposomal oral are the practical routes.",
  },
];

/* Build lookup by id */
window.PEPTIDE_INDEX = Object.fromEntries(window.PEPTIDES.map(p => [p.id, p]));
